// ─── PRODUCT CATALOG FALLBACK (used for DEMO mode and initial load) ───
export const CATALOGO_FALLBACK = [
  { nombre: "Cookies de chocolate y avellanas", precio: 2.60, cat: "Pastelería" },
  { nombre: "Cookies de chocolate blanco y pistachos", precio: 2.80, cat: "Pastelería" },
  { nombre: "Cookie Oreo", precio: 2.30, cat: "Pastelería" },
  { nombre: "Cookies veganas", precio: 2.30, cat: "Pastelería" },
  { nombre: "Cookies de kinder", precio: 2.50, cat: "Pastelería" },
  { nombre: "Brownie", precio: 4.00, cat: "Pastelería" },
  { nombre: "Brownie individual", precio: 1.80, cat: "Pastelería" },
  { nombre: "Brownie 500gr", precio: 16.70, cat: "Pastelería" },
  { nombre: "Brownie San Valentín", precio: 5.00, cat: "Pastelería" },
  { nombre: "Brookie", precio: 3.20, cat: "Pastelería" },
  { nombre: "Brookie San Valentín", precio: 5.00, cat: "Pastelería" },
  { nombre: "Blondie", precio: 2.60, cat: "Pastelería" },
  { nombre: "Viñacaos", precio: 2.50, cat: "Pastelería" },
  { nombre: "Bizcocho de naranja", precio: 3.30, cat: "Pastelería" },
  { nombre: "Bizcocho de limón", precio: 3.00, cat: "Pastelería" },
  { nombre: "Bizcocho de limón 400 g", precio: 12.00, cat: "Pastelería" },
  { nombre: "Bizcocho de Naranja 500gr", precio: 15.00, cat: "Pastelería" },
  { nombre: "Bizcocho de chocolate con nata", precio: 4.50, cat: "Pastelería" },
  { nombre: "Bizcocho chocolate y plátano (grande)", precio: 24.00, cat: "Pastelería" },
  { nombre: "Bizcocho de plátano y chocolate", precio: 3.20, cat: "Pastelería" },
  { nombre: "Magdalenas", precio: 1.50, cat: "Pastelería" },
  { nombre: "Magdalenas (azúcar de coco)", precio: 1.60, cat: "Pastelería" },
  { nombre: "Cupcakes", precio: 3.00, cat: "Pastelería" },
  { nombre: "Bollitos", precio: 1.50, cat: "Panadería" },
  { nombre: "Bollo Adolescente", precio: 1.70, cat: "Panadería" },
  { nombre: "Roll Fresa", precio: 3.20, cat: "Pastelería" },
  { nombre: "Roll Manzana", precio: 3.50, cat: "Pastelería" },
  { nombre: "Rollo de canela", precio: 3.50, cat: "Pastelería" },
  { nombre: "Granola 250Gr.", precio: 6.50, cat: "Pastelería" },
  { nombre: "Arroz con leche", precio: 2.00, cat: "Pastelería" },
  { nombre: "Arroz con leche sin lactosa", precio: 2.00, cat: "Pastelería" },
  { nombre: "Tarta de queso", precio: 5.50, cat: "Pastelería" },
  { nombre: "Tarta de queso sin lactosa", precio: 5.50, cat: "Pastelería" },
  { nombre: "Tarta de queso de pistacho", precio: 6.50, cat: "Pastelería" },
  { nombre: "Tarta de queso de pistacho sin lactosa", precio: 7.50, cat: "Pastelería" },
  { nombre: "Tarta de queso con frutos rojos San Valentín", precio: 7.00, cat: "Pastelería" },
  { nombre: "Tarta queso y pistacho San Valentín", precio: 8.00, cat: "Pastelería" },
  { nombre: "Vasito Tarta de la abuela", precio: 3.00, cat: "Pastelería" },
  { nombre: "Mini tarta", precio: 5.00, cat: "Pastelería" },
  { nombre: "Mini tarta (bizc. choc y crema kinder)", precio: 6.00, cat: "Pastelería" },
  { nombre: "Marquesas de almendra", precio: 1.30, cat: "Pastelería" },
  { nombre: "Pestiños", precio: 1.00, cat: "Pastelería" },
  { nombre: "Porción bizcocho choco", precio: 2.00, cat: "Pastelería" },
  { nombre: "Mini de queso y turrón", precio: 9.00, cat: "Pastelería" },
  { nombre: "Postre chocolate Navidad", precio: 9.50, cat: "Pastelería" },
  { nombre: "Postre de San Valentín", precio: 7.50, cat: "Pastelería" },
  { nombre: "Mantecados de chocolate y almendra", precio: 0.90, cat: "Pastelería" },
  { nombre: "Mantecados de aceite de oliva", precio: 0.90, cat: "Pastelería" },
  { nombre: "Polvorón de almendra", precio: 0.90, cat: "Pastelería" },
  { nombre: "Polvorón de limón", precio: 0.90, cat: "Pastelería" },
  { nombre: "Polvorón de chocolate", precio: 0.90, cat: "Pastelería" },
  { nombre: "Roscos de anís", precio: 1.30, cat: "Pastelería" },
  { nombre: "Tarta de queso y turrón (6-8 pax)", precio: 33.00, cat: "Pastelería" },
  { nombre: "Tarta de queso y turrón (10-12 pax)", precio: 49.00, cat: "Pastelería" },
  { nombre: "Tarta de queso y pistacho (10-12 pax)", precio: 47.00, cat: "Pastelería" },
  { nombre: "Torrijas Azúcar y Canela", precio: 1.80, cat: "Pastelería" },
  { nombre: "Torrijas Azúcar y Canela SIN LACTOSA", precio: 1.80, cat: "Pastelería" },
  { nombre: "Torrijas Miel", precio: 1.80, cat: "Pastelería" },
  { nombre: "Torrijas Miel SIN LACTOSA", precio: 1.80, cat: "Pastelería" },
  { nombre: "Torrijas sin proteína de la leche de la vaca", precio: 1.80, cat: "Pastelería" },
  { nombre: "Barra de pan", precio: 2.00, cat: "Panadería" },
  { nombre: "Hogaza rústica", precio: 5.50, cat: "Panadería" },
  { nombre: "Hogaza Pan de miel y semillas", precio: 5.50, cat: "Panadería" },
  { nombre: "1 kg Hogaza rústica", precio: 11.00, cat: "Panadería" },
  { nombre: "1 kg Hogaza Miel y semillas", precio: 11.00, cat: "Panadería" },
  { nombre: "Pan de molde con semillas 1/2", precio: 6.50, cat: "Panadería" },
  { nombre: "Pan de hamburguesa", precio: 3.00, cat: "Panadería" },
  { nombre: "Chapata", precio: 1.70, cat: "Panadería" },
  { nombre: "Pan de Torrijas", precio: 7.00, cat: "Panadería" },
].sort((a, b) => a.nombre.localeCompare(b.nombre, "es"));

// Pre-computed price lookup (rebuilt when catalog loads from Notion)
export let PRICE_MAP = {};
CATALOGO_FALLBACK.forEach(c => { PRICE_MAP[c.nombre.toLowerCase().trim()] = c.precio; });

export function rebuildPriceMap(catalog) {
  PRICE_MAP = {};
  catalog.forEach(c => { PRICE_MAP[c.nombre.toLowerCase().trim()] = c.precio; });
}

// Most ordered products (for quick access)
export const FRECUENTES = [
  "Cookies de chocolate blanco y pistachos",
  "Cookies de chocolate y avellanas",
  "Viñacaos",
  "Bizcocho de naranja",
  "Brookie",
  "Brownie",
  "Barra de pan",
  "1 kg Hogaza Miel y semillas",
];
